/**
 * QuickReportDialog — Printable study summary (OE2 "Quick-Report" equivalent).
 *
 * Shows a modal with study metadata + series list, with a "Print" button
 * that opens the browser print dialog (user can save as PDF).
 */
import { useTranslation } from 'react-i18next';
import { format } from 'date-fns';
import { Printer, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Study, Series } from '@/shared/types';
import { formatPatientName } from '@/shared/components/ModalityBadge';

interface QuickReportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  study: Study | null;
  series?: Series[];
}

export default function QuickReportDialog({ open, onOpenChange, study, series = [] }: QuickReportDialogProps) {
  const { t } = useTranslation();

  if (!study) return null;

  const handlePrint = () => {
    const printWindow = window.open('', '_blank', 'width=800,height=600');
    if (!printWindow) return;

    const html = `
<!DOCTYPE html>
<html lang="${t('common.lang', { defaultValue: 'en' })}">
<head>
<meta charset="utf-8">
<title>Study Report — ${formatPatientName(study.patientName)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; color: #333; }
  h1 { font-size: 20px; border-bottom: 2px solid #333; padding-bottom: 8px; }
  h2 { font-size: 16px; margin-top: 24px; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th, td { text-align: left; padding: 6px 12px; border-bottom: 1px solid #ddd; font-size: 13px; }
  th { background: #f5f5f5; font-weight: 600; }
  .meta { display: grid; grid-template-columns: 200px 1fr; gap: 4px 16px; margin: 16px 0; }
  .meta dt { font-weight: 600; color: #666; }
  .meta dd { margin: 0; }
  .footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #ddd; padding-top: 8px; }
</style>
</head>
<body>
  <h1>Study Report</h1>
  <dl class="meta">
    <dt>Patient Name</dt><dd>${formatPatientName(study.patientName)}</dd>
    <dt>Patient ID</dt><dd>${study.patientId}</dd>
    <dt>Study Date</dt><dd>${study.studyDate ? format(study.studyDate, 'MMM dd, yyyy') : '—'}</dd>
    <dt>Study Time</dt><dd>${study.studyTime || '—'}</dd>
    <dt>Modality</dt><dd>${study.modalities.join(', ')}</dd>
    <dt>Study Description</dt><dd>${study.studyDescription || '—'}</dd>
    <dt>Accession Number</dt><dd>${study.accessionNumber || '—'}</dd>
    <dt>Referring Physician</dt><dd>${study.referringPhysician?.replace(/\^/g, ', ') || '—'}</dd>
    <dt>Study Instance UID</dt><dd>${study.studyInstanceUID || '—'}</dd>
    <dt>Number of Series</dt><dd>${study.numberOfSeries}</dd>
    <dt>Number of Instances</dt><dd>${study.numberOfInstances}</dd>
  </dl>
  <h2>Series</h2>
  <table>
    <thead><tr><th>#</th><th>Modality</th><th>Description</th><th>Instances</th></tr></thead>
    <tbody>
      ${series.map((s, i) => `<tr><td>${s.seriesNumber ?? i + 1}</td><td>${s.modality}</td><td>${s.seriesDescription || '—'}</td><td>${s.numberOfInstances}</td></tr>`).join('')}
    </tbody>
  </table>
  <div class="footer">Generated by Orthanc Explorer 3 on ${format(new Date(), 'MMM dd, yyyy HH:mm')}</div>
</body>
</html>`;
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 500);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center justify-between">
            {t('studyList.quickReport', { defaultValue: 'Quick Report' })}
            <Button variant="ghost" size="sm" onClick={() => onOpenChange(false)}>
              <X className="h-4 w-4" />
            </Button>
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <dl className="grid grid-cols-[200px_1fr] gap-y-2 text-sm">
            <dt className="font-semibold text-muted-foreground">{t('studies.patientName')}</dt>
            <dd>{formatPatientName(study.patientName)}</dd>
            <dt className="font-semibold text-muted-foreground">{t('studyList.columns.accession')}</dt>
            <dd>{study.accessionNumber || '—'}</dd>
            <dt className="font-semibold text-muted-foreground">{t('studies.studyDate')}</dt>
            <dd>{study.studyDate ? format(study.studyDate, 'MMM dd, yyyy') : '—'}</dd>
            <dt className="font-semibold text-muted-foreground">{t('studyList.columns.modality')}</dt>
            <dd>{study.modalities.join(', ')}</dd>
            <dt className="font-semibold text-muted-foreground">{t('studyList.columns.description')}</dt>
            <dd>{study.studyDescription || '—'}</dd>
            <dt className="font-semibold text-muted-foreground">{t('studyList.columns.referring')}</dt>
            <dd>{study.referringPhysician?.replace(/\^/g, ', ') || '—'}</dd>
          </dl>
          <div className="flex justify-end gap-2">
            <Button variant="outline" size="sm" onClick={() => onOpenChange(false)}>
              {t('common.close', { defaultValue: 'Close' })}
            </Button>
            <Button size="sm" onClick={handlePrint} className="gap-1.5">
              <Printer className="h-3.5 w-3.5" /> {t('studyList.print', { defaultValue: 'Print / Save PDF' })}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
